ktor:
  application:
    modules:
      - com.fugisawa.playlistsgql.ApplicationKt.module
  deployment:
    port: 8080

database:
  driver: "org.postgresql.Driver"
  url: "jdbc:postgresql://localhost:5432/kdb_playlists"
  user: "postgres"
  password: "postgres"
